import dotenv from "dotenv";
dotenv.config();
// variablename: process.env.ENV_NAME_HERE

export default {
  env: process.env.ENV,
  protocol: process.env.PROTOCOL,
  acct: process.env.ACCT,
  acctWif: process.env.ACCTWIF,
  privKey: process.env.HIVE_PRIVATE_KEY,
  pubKey: process.env.HIVE_PUBLIC_KEY,
  threeSpeakPostWif: process.env.THREESPEAK_POSTING_WIF,
  threeSpeakActiveWif: process.env.THREESPEAK_ACTIVE_WIF,
  authWifMemo: process.env.AUTH_WIF_MEMO,
  authPubMemo: process.env.AUTH_PUB_MEMO,
  host: process.env.HOST,
  port: process.env.PORT,
  hot: process.env.HIVE_ONBOARD_TOKEN,
  authApiClientId: process.env.AUTH_API_CLIENT_ID,
  authJwtSecret: process.env.AUTH_JWT_SECRET,
  chatAuthSecret: process.env.CHAT_AUTH_SECRET,
  sessionSecret: process.env.SESSION_SECRET,
  appPageDomain: process.env.APP_PAGE_DOMAIN,
  appEncoderPrivate: process.env.APP_ENCODER_PRIVATE,
  googleKey: process.env.GOOGLE_RECAPTCHA_KEY,
  hiveSqlHost: process.env.HIVESQL_HOST,
  hiveSqlUser: process.env.HIVESQL_USER,
  hiveSqlPass: process.env.HIVESQL_PASSWORD,
  hiveSqlDb: process.env.HIVESQL_DATABASE,
  bunnyCdnSecurityKey: process.env.BUNNY_CDN_SECURITY_KEY,
  encoderSecret: process.env.ENCODER_SECRET,
  wasabiEndpoint: process.env.WASABI_ENDPOINT,
  wasabiAccessKeyId: process.env.WASABI_ACCESS_KEY_ID,
  wasabiSecretKey: process.env.WASABI_SECRET_KEY,
  wasabiRegion: process.env.WASABI_REGION,
  wasabiBucket: process.env.WASABI_BUCKET,
  awsCloudSearchAccessKeyId: process.env.AWS_CLOUDSEARCH_ACCESS_KEY_ID,
  awsCloudSearchSecretKey: process.env.AWS_CLOUDSEARCH_SECRET_KEY,
  awsCloudSearchEndpoint: process.env.AWS_CLOUDSEARCH_ENDPOINT,
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID,
  awsSecretKey: process.env.AWS_SECRET_KEY,
  authSessionSecret: process.env.AUTH_SESSION_SECRET,
};
